// tests/spotify.test.http

@baseUrl = {{$dotenv BASE_URL}}{{$dotenv SPOTIFY_PREFIX}}
@apiKey = {{$dotenv API_KEY}}

###
POST {{baseUrl}}
X-API-KEY: {{apiKey}}
Content-Type: application/json

{
  "method": "GET",
  "path": "/me/tracks",
  "query": {
    "__mode": "ping"
  }
}

### 
POST {{baseUrl}}
X-API-KEY: {{apiKey}}
Content-Type: application/json

{
  "method": "GET",
  "path": "/me"  
}

###

POST {{baseUrl}}
X-API-KEY: {{apiKey}}
Content-Type: application/json

{
  "method": "GET",
  "path": "/me/top/tracks"
}

###

POST {{baseUrl}}
X-API-KEY: {{apiKey}}
Content-Type: application/json

{
  "method": "GET",
  "path": "/me/following",
  "query": {
    "type": "artist"    
  }
}

###

POST {{baseUrl}}
X-API-KEY: {{apiKey}}
Content-Type: application/json

{
  "method": "GET",
  "path": "/artists",
  "query": {
    "ids": "5KSlWH59lUrTux2gOtW1Qm,2RVXnU56kIClg1UbAW9ehz"
  }
}
