// tests/spotify.test.http

@baseUrl = {{$dotenv BASE_URL}}{{$dotenv SPOTIFY_PREFIX}}
@apiKey = {{$dotenv API_KEY}}


### Tracks Get

GET {{baseUrl}}/tracks
X-API-KEY: {{apiKey}}
Content-Type: application/json

### Tracks Refresh

POST {{baseUrl}}/tracks/refresh
X-API-KEY: {{apiKey}}
Content-Type: application/json

### =========================================================

### Following Get

GET {{baseUrl}}/following
X-API-KEY: {{apiKey}}
Content-Type: application/json

### Following Refresh

POST {{baseUrl}}/following/refresh
X-API-KEY: {{apiKey}}
Content-Type: application/json

### =========================================================

### Playlist Get

GET {{baseUrl}}/playlists
X-API-KEY: {{apiKey}}
Content-Type: application/json

### Playlist Refresh

POST {{baseUrl}}/playlists/refresh
X-API-KEY: {{apiKey}}
Content-Type: application/json

### =========================================================

### Artists Get
GET {{baseUrl}}/artists?ids=1uNFoZAHBGtllmzznpCI3s,3eOyGULyH8dDoCBQMuLYZC
X-API-KEY: {{apiKey}}
Content-Type: application/json

### Artists Refresh
POST {{baseUrl}}/artists/refresh
X-API-KEY: {{apiKey}}
Content-Type: application/json

{
  "artistIds": [
    "1uNFoZAHBGtllmzznpCI3s",
    "3eOyGULyH8dDoCBQMuLYZC"
  ],
  "force": true
}

### =========================================================

### Album Get
GET {{baseUrl}}/albums?ids=5cxMa6oLINJzmZ8lF7wWQN,05H1dRhfSFcuWW1HD5Nama
X-API-KEY: {{apiKey}}
Content-Type: application/json

### Albums Refresh
POST {{baseUrl}}/albums/refresh
X-API-KEY: {{apiKey}}
Content-Type: application/json

{
  "albumIds": [
    "5cxMa6oLINJzmZ8lF7wWQN",
    "05H1dRhfSFcuWW1HD5Nama"
  ],
  "force": true
}