@host = {{$dotenv BASE_URL}}/{{$dotenv PREFIX}}
@apikey = {{$dotenv API_KEY}}

### 🎧 Top Tracks
GET {{host}}?path=/me/top/tracks
X-API-KEY: {{apikey}}

### 💿 Saved Albums
GET {{host}}?path=/me/albums
X-API-KEY: {{apikey}}

### 👤 Artist Info
GET {{host}}?path=/artists/6eUKZXaKkcviH0Ku9w2n3V
X-API-KEY: {{apikey}}

### 📀 Playlist Info
GET {{host}}?path=/playlists/37i9dQZF1DXcBWIGoYBM5M
X-API-KEY: {{apikey}}